---
shortcuts:
  commands:
    "<Super>Return": exo-open --launch TerminalEmulator
    "<Super>b": exo-open --launch WebBrowser
    "<Super>l": xflock4
  wm:
    left_workspace: "<Super>Left"
    right_workspace: "<Super>Right"
    up_workspace: "<Super>Up"
    down_workspace: "<Super>Down"
    workspace_1: "<Super>1"
    workspace_2: "<Super>2"
    workspace_3: "<Super>3"
    workspace_4: "<Super>4"
settings:
  xfwm4:
    "/general/easy_click": Super
    "/general/cycle_tabwin_mode": 1
  xfce4-session:
    "/compat/LaunchGNOME": true
  xfce4-panel:
    "/panels/dark-mode": true
panels:
- icon-size: 16
  length: 100
  position: p=10;x=0;y=0
  position-locked: true
  size: 30
  plugins:
  - - whiskermenu
  - - tasklist
  - - separator
    - expand: true
      style: 0
  - - windowmenu
  - - pager
  - - systray
    - icon-size: 16
      square-icons: true
  - - pulseaudio
    - enable-keyboard-shortcuts: true
  - - power-manager-plugin
  - - notification-plugin
  - - clock
    - digital-layout: 3
